# ── Variables & Font ──────────────────────────────────────────────────────────
# Mod1 = Alt (Primary $mod), Mod4 = Super / Windows Key

set $mod Mod1
set $super Mod4

# Font for window titles
font pango:JetBrainsMono Nerd Font 10

# Drag floating windows
floating_modifier $mod
tiling_drag modifier titlebar
popup_during_fullscreen all

# Window layout defaults
default_border pixel 0
default_floating_border pixel 0
focus_on_window_activation focus
