# ── Window Rules & Floating Criteria ──────────────────────────────────────────
for_window [class="Pavucontrol"] floating enable
for_window [class="Lxappearance"] floating enable
for_window [class="File-roller"] floating enable
for_window [class="[cC]opy[qQ]"] floating enable, resize set 650 500, move position center
for_window [instance="scratchpad_term"] floating enable, resize set 900 550, move position center, move to scratchpad
for_window [class="(?i)(songrec|re\.fossplant\.songrec)"] floating enable, resize set 850 620, move position center
