# ── Window Rules & Floating Criteria ──────────────────────────────────────────
for_window [floating] border pixel 0
for_window [window_role="pop-up"] floating enable, border pixel 0
for_window [window_type="dialog"] floating enable, border pixel 0
for_window [window_type="utility"] floating enable, border pixel 0

for_window [class="Pavucontrol"] floating enable, border pixel 0
for_window [class="Lxappearance"] floating enable, border pixel 0
for_window [class="File-roller"] floating enable, border pixel 0
for_window [class="[cC]opy[qQ]"] floating enable, resize set 650 500, move position center, border pixel 0
for_window [instance="scratchpad_term"] floating enable, resize set 900 550, move position center, move to scratchpad, border pixel 0
for_window [class="(?i)(songrec|re\.fossplant\.songrec)"] floating enable, resize set 850 620, move position center, border pixel 0
for_window [class="CavaPopup"] floating enable, resize set 820 240, move position center, border pixel 0
for_window [class="(?i)ripdrag"] floating enable, border pixel 0
