# Pastel Powerline (Typecraft Capsule) Starship Prompt
"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 300
command_timeout = 1000
add_newline = false

format = """
[](#3B4252)\
$os\
$username\
[](bg:#F4A261 fg:#3B4252)\
$directory\
[](fg:#F4A261 bg:#A6E3A1)\
$git_branch\
$git_status\
[](fg:#A6E3A1 bg:#89B4FA)\
$c\
$rust\
$golang\
$nodejs\
$bun\
$python\
$java\
$php\
$ruby\
$docker_context\
[](fg:#89B4FA bg:#E8AEB7)\
$time\
[ ](fg:#E8AEB7)\
$line_break\
$character"""

# ----------------- OS & Username -----------------
[os]
disabled = false
style = "bg:#3B4252 fg:#ECEFF4"
format = '[$symbol ]($style)'

[os.symbols]
Arch = "󰣇"
Ubuntu = "󰕈"
Debian = "󰣚"
Fedora = "󰣛"
Macos = "󰀵"
Windows = "󰍲"
Linux = "󰌽"

[username]
show_always = true
style_user = "bg:#3B4252 fg:#ECEFF4"
style_root = "bg:#3B4252 fg:#BF616A"
format = '[$user]($style)'
disabled = false

# ----------------- Directory -----------------
[directory]
style = "bg:#F4A261 fg:#1E1E2E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

# ----------------- Git -----------------
[git_branch]
symbol = ""
style = "bg:#A6E3A1 fg:#1E1E2E"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#A6E3A1 fg:#1E1E2E"
format = '[$all_status$ahead_behind ]($style)'

# ----------------- Languages & Runtimes -----------------
[c]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol($version) ]($style)'

[golang]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol($version) ]($style)'

[bun]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol($version) ]($style)'

[python]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol($version) ]($style)'

[java]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol($version) ]($style)'

[php]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol($version) ]($style)'

[ruby]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#89B4FA fg:#1E1E2E"
format = '[ $symbol$context ]($style)'

# ----------------- Time -----------------
[time]
disabled = false
time_format = "%R"
style = "bg:#E8AEB7 fg:#1E1E2E"
format = '[ 󰥔 $time ]($style)'

# ----------------- Character -----------------
[character]
disabled = false
success_symbol = '[➜](bold green) '
error_symbol = '[➜](bold red) '
