Net/ThemeName "catppuccin-mocha-mauve-standard+default"
Net/IconThemeName "Papirus-Dark"
Gtk/CursorThemeName "Bibata-Modern-Classic"
Gtk/FontName "JetBrainsMono Nerd Font 11"
Gtk/DecorationLayout "menu:close"
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
