[package]
name = "desktop-music-daemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "desktop-music-daemon"
path = "src/main.rs"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
zbus = { version = "5", default-features = false, features = ["tokio"] }
futures-lite = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
